name: TEST

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHORT_SHA: ${{ git rev-parse --short HEAD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Echo
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Echo2
        run: echo ${SHORT_SHA}
